countries = {"Afghanistan","Africa","Albania","Algeria","Andorra","Angola",
"Anguilla","Antigua-and-Barbuda","Argentina","Armenia","Aruba","Australia",
"Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus",
"Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia","Bosnia-and-Herzegovina",
"Botswana","Brazil","British-Virgin-Islands","Brunei","Brunei-","Bulgaria",
"Burkina-Faso","Burundi","Cabo-Verde","Cambodia","Cameroon","Canada","CAR",
"Caribbean-Netherlands","Cayman-Islands","Chad","Channel-Islands","Chile","China",
"Colombia","Congo","Costa-Rica","Croatia","Cuba","Cura&ccedil;ao","Cyprus",
"Czechia","Denmark","Diamond-Princess","Diamond-Princess-","Djibouti","Dominica",
"Dominican-Republic","DRC","Ecuador","Egypt","El-Salvador","Equatorial-Guinea",
"Eritrea","Estonia","Eswatini","Ethiopia","Faeroe-Islands","Falkland-Islands",
"Fiji","Finland","France","French-Guiana","French-Polynesia","Gabon","Gambia",
"Georgia","Germany","Ghana","Gibraltar","Greece","Greenland","Grenada",
"Guadeloupe","Guam","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti",
"Honduras","Hong-Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq",
"Ireland","Isle-of-Man","Israel","Italy","Ivory-Coast","Jamaica","Japan","Jordan",
"Kazakhstan","Kenya","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Liberia",
"Libya","Liechtenstein","Lithuania","Luxembourg","Macao","Madagascar","Malawi",
"Malaysia","Maldives","Mali","Malta","Martinique","Mauritania","Mauritius",
"Mayotte","Mexico","Moldova","Monaco","Mongolia","Montenegro","Montserrat",
"Morocco","Mozambique","MS-Zaandam","MS-Zaandam-","Myanmar","Namibia","Nepal",
"Netherlands","New-Caledonia","New-Zealand","Nicaragua","Niger","Nigeria",
"North-Macedonia","Norway","Oman","Pakistan","Palestine","Panama",
"Papua-New-Guinea","Paraguay","Peru","Philippines","Poland","Portugal",
"Puerto-Rico","Qatar","Romania","Russia","Rwanda","S-Korea",
"Saint-Kitts-and-Nevis","Saint-Lucia","Saint-Martin","Saint-Pierre-Miquelon",
"San-Marino","Sao-Tome-and-Principe","Saudi-Arabia","Senegal","Serbia",
"Seychelles","Sierra-Leone","Singapore","Sint-Maarten","Slovakia","Slovenia",
"Somalia","South-Africa","South-Sudan","Spain","Sri-Lanka","St-Barth",
"St-Vincent-Grenadines","Sudan","Suriname","Sweden","Switzerland","Syria",
"Taiwan","Tanzania","Thailand","Timor-Leste","Togo","Trinidad-and-Tobago",
"Tunisia","Turkey","Turks-and-Caicos","UAE","Uganda","UK","Ukraine","Uruguay",
"US-Virgin-Islands","USA","Uzbekistan","Vatican-City","Venezuela","Vietnam",
"Western-Sahara","Zambia","Zimbabwe"}

lower_countries = ['benin', 'ivory-coast', 'papua-new-guinea', 'channel-islands', 
'guadeloupe', 'africa', 'turkey', 'antigua-and-barbuda', 'diamond-princess-', 
'guinea', 'bahamas', 'belgium', 'south-africa', 'libya', 'tunisia', 'liechtenstein', 
'belize', 'djibouti', 'sudan', 'syria', 'greenland', 'pakistan', 'cayman-islands', 
'angola', 'kuwait', 'sri-lanka', 'montserrat', 'western-sahara', 'chile', 'anguilla', 
'canada', 'cambodia', 'costa-rica', 's-korea', 'ms-zaandam', 'finland', 'honduras', 
'russia', 'switzerland', 'albania', 'czechia', 'peru', 'bangladesh', 'algeria', 
'french-guiana', 'iceland', 'montenegro', 'guam', 'guinea-bissau', 'south-sudan', 
'philippines', 'thailand', 'serbia', 'togo', 'azerbaijan', 'morocco', 'new-zealand', 
'cyprus', 'seychelles', 'andorra', 'indonesia', 'kazakhstan', 'martinique', 'paraguay', 
'saint-martin', 'israel', 'mayotte', 'sierra-leone', 'el-salvador', 'bolivia', 
'sao-tome-and-principe', 'qatar', 'gibraltar', 'isle-of-man', 'kyrgyzstan', 'panama', 
'senegal', 'argentina', 'norway', 'nigeria', 'mongolia', 'fiji', 'denmark', 'vietnam', 
'eswatini', 'ecuador', 'armenia', 'mauritius', 'madagascar', 'liberia', 'mauritania', 
'guatemala', 'malaysia', 'brazil', 'ms-zaandam-', 'somalia', 'monaco', 'zambia', 
'afghanistan', 'bermuda', 'france', 'nepal', 'saint-pierre-miquelon', 'dominica', 
'luxembourg', 'nicaragua', 'maldives', 'barbados', 'moldova', 'palestine', 
'diamond-princess', 'gabon', 'st-barth', 'rwanda', 'japan', 'iraq', 'puerto-rico', 
'guyana', 'ghana', 'uae', 'latvia', 'spain', 'zimbabwe', 'lithuania', 
'st-vincent-grenadines', 'falkland-islands', 'myanmar', 'uruguay', 'mali', 'ireland', 
'netherlands', 'niger', 'portugal', 'mexico', 'kenya', 'lebanon', 'cameroon', 
'turks-and-caicos', 'germany', 'suriname', 'vatican-city', 'brunei-', 'ethiopia', 
'hungary', 'macao', 'ukraine', 'uzbekistan', 'dominican-republic', 'uk', 
'faeroe-islands', 'iran', 'belarus', 'bosnia-and-herzegovina', 'british-virgin-islands', 
'india', 'congo', 'usa', 'eritrea', 'sweden', 'new-caledonia', 'saint-kitts-and-nevis', 
'cuba', 'equatorial guinea', 'timor-leste', 'singapore', 'croatia', 'bulgaria', 
'trinidad-and-tobago', 'us-virgin-islands', 'burkina faso', 'chad', 'brunei', 'uganda', 
'oman', 'jordan', 'saint-lucia', 'poland', 'namibia', 'tanzania', 'romania', 'sint-maarten', 
'greece', 'saudi-arabia', 'botswana', 'china', 'colombia', 'aruba', 'grenada', 'car', 'haiti', 
'bahrain', 'egypt', 'mozambique', 'caribbean-netherlands', 'hong-kong', 'malawi', 'laos', 
'san-marino', 'slovenia', 'austria', 'malta', 'cabo-verde', 'estonia', 'slovakia', 'taiwan', 
'bhutan', 'italy', 'jamaica', 'north-macedonia', 'venezuela','french-polynesia', 'drc', 
'australia', 'burundi', 'gambia', 'georgia', 'usa',]